openapi: 3.0.0
info:
  title: Domain Restricted Login API
  description: API that allows only users with @sungkwang.hs.kr domain to log in.
  version: 1.0.0
servers:
  - url: https://api.yourdomain.com
    description: Production server
paths:
  /login:
    post:
      summary: User login with domain restriction
      description: "Logs a user in only if their email is from @sungkwang.hs.kr domain."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@sungkwang.hs.kr
                password:
                  type: string
                  format: password
                  example: strongpassword123
      responses:
        '200':
          description: "Successful login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT token for accessing protected resources
        '400':
          description: "Invalid email domain"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Error message explaining why login failed"
        '401':
          description: "Invalid credentials"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Error message indicating wrong email or password"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Authorization header using the Bearer scheme.
security:
  - bearerAuth: []
